services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
